development: &defaults
  # Used by mailers and models as hostname to generate URLs to Alonetone.
  url: localhost:3000
  # Default FROM address when sending email.
  email: support@example.com
  # Secret key base used by Rails (normally configured in config/secrets.yml)
  secret: ~
  # Type of storage provider to use, see config/storage.yml for options.
  storage_service: filesystem
  # When set to true the controllers will serve a dummy MP3 instead of
  # uploaded data.
  play_dummy_mp3s: false
  # Amazon CloudFront and S3 configuration. Leave blank when using disk based
  # storage.
  amazon_access_key_id: ~
  amazon_secret_access_key: ~
  amazon_s3_region: ~
  amazon_s3_bucket_name: ~
  amazon_cloud_front_domain_name: ~
  amazon_cloud_front_key_pair_id: ~
  # API token to use when accessing Askimet for spam filtering. You can
  # register at https://akismet.com.
  rakismet_key: ~
  # Google Analytics property ID.
  ga: ~
  # Configure to start using Clicky. You can register at https://clicky.com/.
  get_clicky: ~
  # Configure Typekit token to start using Typekit for fonts.
  typekit: ~
  # Deprecated: used by Greenfield views as hostname for URLs linking to
  # Greenfield.
  greenfield_url: localhost:3000

test:
  <<: *defaults
  url: alonetone.example.com
  storage_service: temporary
  play_dummy_mp3s: false
  rakismet_key: unusable