development:
  secret_key_base: <%= Alonetone.secret || SecureRandom.hex(64) %>
test:
  secret_key_base: <%= Alonetone.secret || SecureRandom.hex(64) %>
production:
  secret_key_base: <%= Alonetone.secret %>
